const frases = [
  { categoria: "Película", frase: ["El señor de los anillos"] },
  { categoria: "Película", frase: ["La vida es bella"] },
  { categoria: "Película", frase: ["El padrino"] },
  { categoria: "Película", frase: ["Pulp Fiction"] },
  { categoria: "Película", frase: ["Jurassic Park"] },
  { categoria: "Película", frase: ["El club de la lucha"] },
  { categoria: "Película", frase: ["Forrest Gump"] },
  { categoria: "Película", frase: ["Matrix"] },
  { categoria: "Película", frase: ["Titanic"] },
  { categoria: "Película", frase: ["El rey león"] },
  { categoria: "Serie", frase: ["Juego de tronos"] },
  { categoria: "Serie", frase: ["Breaking Bad"] },
  { categoria: "Serie", frase: ["La casa de papel"] },
  { categoria: "Serie", frase: ["Stranger Things"] },
  { categoria: "Serie", frase: ["Los Simpsons"] },
  { categoria: "Serie", frase: ["Friends"] },
  { categoria: "Serie", frase: ["El método Kominsky"] },
  { categoria: "Refrán", frase: ["A caballo regalado no le mires el diente"] },
  { categoria: "Refrán", frase: ["No hay mal que por bien no venga"] },
  { categoria: "Refrán", frase: ["Más vale tarde que nunca"] },
  { categoria: "Refrán", frase: ["En boca cerrada no entran moscas"] },
  { categoria: "Refrán", frase: ["Camarón que se duerme la corriente lo lleva"] },
  { categoria: "Personaje", frase: ["Harry Potter"] },
  { categoria: "Personaje", frase: ["Sherlock Holmes"] },
  { categoria: "Personaje", frase: ["Don Quijote de la Mancha"] },
  { categoria: "Personaje", frase: ["Darth Vader"] },
  { categoria: "Personaje", frase: ["Hermione Granger"] },
  { categoria: "Lugar", frase: ["La Torre Eiffel"] },
  { categoria: "Lugar", frase: ["La Gran Muralla China"] },
  { categoria: "Lugar", frase: ["Las Cataratas del Iguazú"] },
  { categoria: "Canción", frase: ["Bohemian Rhapsody"] },
  { categoria: "Canción", frase: ["Despacito"] },
  { categoria: "Canción", frase: ["La Macarena"] },
  { categoria: "Canción", frase: ["El baile del gorila"] },
  { categoria: "Videojuego", frase: ["The Legend of Zelda"] },
  { categoria: "Videojuego", frase: ["Super Mario Bros"] },
  { categoria: "Videojuego", frase: ["Minecraft"] },
  { categoria: "Videojuego", frase: ["Grand Theft Auto"] },
];

export default frases;
